name: API Tests with Newman

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  api-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm ci
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
    
    - name: Install Newman
      run: npm install -g newman
    
    - name: Start Backend Server
      run: |
        npm start &
        sleep 10
      env:
        NODE_ENV: test
      working-directory: ./backend
    
    - name: Run API Tests
      run: npm run api:test:ci
      env:
        CI: true
        NODE_ENV: test
    
    - name: Upload API Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: newman-api-results
        path: |
          test-results/newman-report.json
          test-results/newman-report.xml
        retention-days: 30

  api-tests-matrix:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm ci
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
    
    - name: Install Newman
      run: npm install -g newman
    
    - name: Start Backend Server
      run: |
        npm start &
        sleep 10
      env:
        NODE_ENV: test
      working-directory: ./backend
    
    - name: Run API Tests
      run: npm run api:test:ci
      env:
        CI: true
        NODE_ENV: test
    
    - name: Upload API Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: newman-api-results-${{ matrix.os }}
        path: |
          test-results/newman-report.json
          test-results/newman-report.xml
        retention-days: 30 