name: Code Coverage

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  coverage:
    timeout-minutes: 30
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm ci
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Start Backend Server
      run: |
        npm start &
        sleep 10
      env:
        NODE_ENV: test
      working-directory: ./backend
    
    - name: Start Frontend Server
      run: |
        npm start &
        sleep 15
      env:
        REACT_APP_API_URL: http://localhost:3001
      working-directory: ./frontend
    
    - name: Run Playwright Tests with Coverage
      run: npx playwright test --reporter=html,junit --reporter-junit-export=test-results/playwright-coverage.xml
      env:
        CI: true
        NODE_ENV: test
    
    - name: Run API Tests with Coverage
      run: npm run api:test:ci
      env:
        CI: true
        NODE_ENV: test
    
    - name: Upload Test Coverage Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-coverage-results
        path: |
          test-results/
          playwright-report/
        retention-days: 30 